STEER_LEFTLIMIT = 145
STEER_RIGHTLIMIT = 95
STEER_STRAIGHT = 120

SHIFT_FORWARD = 1
SHIFT_STOP = 0
SHIFT_BACKWARD = -1

SPEED_LIMIT = 50

LED_ON = True
LED_OFF = False

HEADLIGHT_THRESHOLD = 50

CRUISE_ON = 1
CRUISE_OFF = 0
CRUISE_MINIMUM = 40

WAVE_MAX_DISTANCE = 300
WAVE_MAX_DURATION = (WAVE_MAX_DISTANCE * 2 * 29.1)
BACKDISTANCE_UNKNOWN = -1
BACKDISTANCE_MINIMUM = 10

DRIVE_DELAY = 0.01
CONTROL_IGNORE = 0.5

DRIVE_AUTO = True
DRIVE_MANUAL = False

# BOARD GPIO PIN NUMBER
DC_ENA = 40
DC_IN1 = 38
DC_IN2 = 36
SERVO = 33
BACKLIGHT = 11
HEADLIGHT = 12
BREAKLIGHT = 13
WAVE_TRIG = 24
WAVE_ECHO = 26
